/***
--- !Test
options:
  all_solutions: true
expected: !Result
  status: ALL_SOLUTIONS
  solution: !SolutionSet
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - false
    - false
    - false
    Roots:
    - false
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - false
    - false
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - false
    - true
    - false
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - false
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - false
    - false
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - false
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - false
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - false
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - false
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - false
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - false
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - false
    - false
    GraphNodes:
    - false
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - false
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - false
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - true
    GraphNodes:
    - false
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - false
    - true
    GraphNodes:
    - false
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - false
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - false
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - false
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - false
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - false
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - true
    GraphNodes:
    - false
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - false
    - true
    GraphNodes:
    - false
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - false
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - false
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - false
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - false
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - false
    - false
    GraphNodes:
    - false
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - false
    - true
    GraphNodes:
    - false
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - false
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - false
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - false
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - true
    - true
    - true
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - true
    - true
    - false
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - false
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - false
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - false
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
  - !Solution
    GraphEdges:
    - true
    - true
    - false
    - true
    - true
    - true
    GraphNodes:
    - true
    - true
    - true
    Roots:
    - false
    - true
    - true
***/

include "reachable_multiroot.mzn";

include "reachable.mzn";
include "subgraph.mzn";

%-------------------------------------------------------------------------------

array[GRAPH_NODES] of var bool: GraphNodes; % free variable
array[GRAPH_EDGES] of var bool: GraphEdges; % free variable
array[GRAPH_NODES] of var bool: Roots;      % free variable

%===============================================================================

int: NUM_GRAPH_NODES = 3; % par
int: NUM_GRAPH_EDGES = length(j,i in GRAPH_NODES where i != j)(1);
array[GRAPH_EDGES] of tuple(GRAPH_NODES,GRAPH_NODES): GRAPH_NODE_PAIRS = [ (j,i) | j,i in GRAPH_NODES where i != j ];

%-------------------------------------------------------------------------------

enum GRAPH_NODES = GN(1..NUM_GRAPH_NODES);
enum GRAPH_EDGES = GE(1..NUM_GRAPH_EDGES);

array[GRAPH_EDGES] of GRAPH_NODES: GRAPH_LEAVING_NODE  = [ p.1 | p in GRAPH_NODE_PAIRS ];
array[GRAPH_EDGES] of GRAPH_NODES: GRAPH_ENTERING_NODE = [ p.2 | p in GRAPH_NODE_PAIRS ];

constraint subgraph(
  GRAPH_LEAVING_NODE,
  GRAPH_ENTERING_NODE,
  GraphNodes,
  GraphEdges
);

%-------------------------------------------------------------------------------

constraint dreachable_multiroot(GRAPH_LEAVING_NODE, GRAPH_ENTERING_NODE, Roots, GraphNodes, GraphEdges)

% List all roots.
