predicate fzn_dreachable_multiroot_reif(int: N, int: E, array[int] of int: from, array[int] of int: to,
                                        array[int] of var bool: rs, array[int] of var bool: ns, array[int] of var bool: es,
                                        var bool: b) =
  abort("Reified dreachable_multiroot constraint is not supported");

%-----------------------------------------------------------------------------%
