predicate fzn_dreachable_multiroot_reif(array[$$E] of $$N: from, array[$$E] of $$N: to,
                                        array[$$N] of var bool: rs, array[$$N] of var bool: ns, array[$$E] of var bool: es,
                                        var bool: b) =
  abort("Reified dreachable_multiroot constraint is not supported");

%-----------------------------------------------------------------------------%
