
predicate lex_lesseq_bool(array[int] of var bool: x ::promise_ctx_antitone,
                          array[int] of var bool: y ::promise_ctx_monotone) ::mzn_deprecated("2.6.0","https://www.minizinc.org/doc-2.6.0/en/lib-globals.html#deprecated");
predicate lex_leq_bool(array[int] of var bool: x ::promise_ctx_antitone,
                       array[int] of var bool: y ::promise_ctx_monotone) ::mzn_deprecated("2.6.0","https://www.minizinc.org/doc-2.6.0/en/lib-globals.html#deprecated");
