predicate lex_lesseq_set(array[int] of var set of int: x,
                         array[int] of var set of int: y) ::mzn_deprecated("2.6.0","https://www.minizinc.org/doc-2.6.0/en/lib-globals.html#deprecated");
predicate lex_leq_set(array[int] of var set of int: x,
                      array[int] of var set of int: y) ::mzn_deprecated("2.6.0","https://www.minizinc.org/doc-2.6.0/en/lib-globals.html#deprecated");
