
predicate lex_less_set(array[int] of var set of int: x,
                       array[int] of var set of int: y) ::mzn_deprecated("2.6.0","https://www.minizinc.org/doc-2.6.0/en/lib-globals.html#deprecated");
predicate lex_lt_set(array[int] of var set of int: x,
                     array[int] of var set of int: y) ::mzn_deprecated("2.6.0","https://www.minizinc.org/doc-2.6.0/en/lib-globals.html#deprecated");
