predicate lex_less_float(array[int] of var float: x ::promise_ctx_antitone,
                         array[int] of var float: y ::promise_ctx_monotone) ::mzn_deprecated("2.6.0","https://www.minizinc.org/doc-2.6.0/en/lib-globals.html#deprecated");

predicate lex_lt_float(array[int] of var float: x ::promise_ctx_antitone,
                       array[int] of var float: y ::promise_ctx_monotone) ::mzn_deprecated("2.6.0","https://www.minizinc.org/doc-2.6.0/en/lib-globals.html#deprecated");
