/***
!Test
expected: !Result
  solution: !SolutionSet
  - !Solution
    a:
    - 3
    - 2
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 1
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 2
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 3
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 4
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 5
    - 1
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 1
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 2
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 3
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 4
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 5
    - 2
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 1
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 2
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 3
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 4
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 5
    - 3
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 1
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 2
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 5
    - 3
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 4
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 5
    - 4
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 1
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 2
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 4
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 4
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 5
    - 3
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 1
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 1
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 2
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 2
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 3
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 5
    - 3
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 5
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 5
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 5
    - 4
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 1
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 1
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 1
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 2
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 2
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 2
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 3
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 3
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 4
    - 3
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 1
    - 4
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 2
    - 4
    - 5
    - 5
    n: 3
  - !Solution
    a:
    - 3
    - 4
    - 5
    - 5
    n: 3
options:
  all_solutions: true
***/

include "nvalue.mzn";

array[1..4] of var 1..5: a ::add_to_output;
var 1..10: n ::add_to_output;

constraint nvalue(n, [1, 1, 2, 2, 3, 3]);
constraint nvalue(4, [3, 1, 7, 16]);
constraint nvalue(3, a);

solve satisfy;

output [
   "a = array1d(1..4, ", show(a), ");\n",
   "n = ", show(n), ";\n"
];
