#line 2 "lib/lexer.yy.cpp"

#line 4 "lib/lexer.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 118
#define YY_END_OF_BUFFER 119
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[378] =
    {   0,
        0,    0,  119,  117,    2,    1,  117,  117,  117,    7,
      117,   16,   83,   79,   81,   16,   85,   10,   10,   16,
       89,   99,   93,  113,    3,  117,    5,   19,  117,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,   16,  101,
        0,  115,  114,    7,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       87,  103,   17,  111,    0,   10,    0,    0,    0,   18,
      105,   91,   97,   95,  113,    4,  109,    0,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,

       38,   42,  113,  113,  113,  113,  113,   52,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,    6,  114,
        0,   84,   80,    0,   82,    0,   86,    0,   90,    0,
        0,  100,    0,   94,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   13,    0,   15,   12,   11,  107,
        0,  116,   20,   22,  113,  113,  113,  113,  113,  113,
       28,  113,  113,  113,  113,  113,  113,  113,   44,   45,
      113,  113,   48,   50,  113,   55,  113,  113,  113,   58,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,

      113,  113,   74,  113,   77,  102,   88,  104,  112,  106,
        0,   92,   98,   96,  110,    0,    0,   43,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  113,  113,   24,
       25,  113,  113,   30,   32,  113,   35,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,   65,  113,   68,   69,    8,  113,   71,  113,
      113,  113,  108,    0,   29,    0,   49,   51,    0,    0,
        0,    0,   78,    0,   14,  113,   23,  113,  113,  113,
       34,    9,   36,  113,  113,  113,  113,  113,  113,  113,
      113,  113,   59,  113,  113,  113,  113,   70,   72,  113,

       76,   31,    0,    0,    0,    0,    0,  113,  113,  113,
       33,  113,  113,  113,  113,  113,   54,  113,   57,  113,
       60,   61,  113,  113,  113,    0,    0,    0,    0,   73,
      113,  113,   27,  113,   39,  113,  113,  113,  113,   53,
      113,  113,  113,    0,   62,    0,    0,  113,  113,   37,
      113,   46,   47,  113,   63,   66,  113,    0,    0,    0,
      113,  113,   40,   56,  113,    0,   64,   67,   21,   26,
      113,   41,  113,  113,  113,   75,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    1,    8,    9,
        9,   10,   11,    9,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   17,   17,   18,    9,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   23,   22,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   24,   24,   39,   40,   41,
       42,   43,   24,   44,   45,   46,   47,   48,   49,   50,
       51,   52,    9,   53,    9,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[54] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    1,    1,    1,
        1,    4,    4,    5,    1,    1,    1,    6,    7,    4,
        4,    4,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1
    } ;

static yyconst flex_int16_t yy_base[386] =
    {   0,
        0,    0,  448,  449,  449,  449,  427,  441,    0,    0,
       50,  449,  449,  434,  423,  430,  416,   88,   50,  423,
       60,  420,  419,    0,  385,  423,  449,  449,    0,   14,
      394,   26,   40,   18,   47,   40,  401,   68,  392,   52,
       49,  399,   78,   84,  391,  401,  393,  387,  401,  449,
      422,  449,    0,    0,  406,  417,   74,   81,   88,  107,
      124,  125,  410,  385,  381,  379,  378,   62,  378,  376,
      449,  449,  449,  449,  124,  133,  142,  101,    0,  449,
      396,  449,  449,  449,    0,  449,  449,  387,   96,  371,
      372,  368,  371,  376,   88,  365,  118,  370,  366,  366,

        0,  120,  360,  355,  363,  370,  356,    0,  355,  356,
      365,  366,  351,  350,  356,  350,  112,  363,  352,  346,
      356,  342,  345,  344,  348,  341,  350,  339,  449,    0,
      374,  449,  449,  373,  449,  372,  449,  371,  449,  152,
      370,  449,  369,  449,  368,  367,  126,  126,  341,  327,
      132,  332,  333,  326,  153,  162,  165,  168,    0,  449,
      340,  449,  326,    0,  337,  327,  331,  319,  333,  327,
        0,  327,  322,  319,  313,  327,  324,  316,  320,    0,
      315,  314,    0,    0,  308,    0,  317,  307,  310,    0,
      299,  308,  300,  310,  299,  302,  295,  299,  305,  299,

      303,  294,  297,  290,    0,  449,  449,  449,  449,  449,
      325,  449,  449,  449,  449,  297,  323,  449,  296,  321,
      320,  282,  292,  285,  282,  315,  174,  276,  270,    0,
        0,  274,  272,    0,  280,  282,    0,  282,  269,  268,
      266,  268,  271,  270,  262,  270,  263,  261,  271,  263,
      269,  258,    0,  268,    0,    0,    0,  266,    0,  258,
      268,  263,  449,  288,  449,  251,  449,  449,  260,  249,
      259,  250,  449,  177,  180,  260,    0,  245,  249,  252,
        0,    0,    0,  248,  252,  239,  245,  244,  235,  248,
      246,  243,    0,  241,  230,  230,  236,    0,    0,  232,

        0,  449,  227,  225,  225,  231,  260,  221,  236,  219,
        0,  222,  229,  228,  209,  208,    0,  229,    0,  207,
        0,    0,  223,  221,  209,  220,  245,  218,  216,  449,
      212,  211,    0,  207,    0,  215,  212,  211,  198,    0,
      197,  207,  213,  208,  449,  193,  203,  195,  195,    0,
      189,    0,    0,  200,    0,    0,  189,  186,  223,  200,
      158,  142,    0,    0,  137,  156,  449,  449,    0,    0,
      130,  449,  100,   63,   59,    0,  449,  197,  201,  206,
      211,  214,  217,  221,  223
    } ;

static yyconst flex_int16_t yy_def[386] =
    {   0,
      377,    1,  377,  377,  377,  377,  377,  378,  379,  380,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  381,  377,  377,  377,  377,  382,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  377,  377,
      378,  377,  383,  380,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  384,  377,
      377,  377,  377,  377,  381,  377,  377,  385,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  377,  383,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  384,  377,
      385,  377,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  377,  377,  377,  377,  377,  377,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  377,  377,  377,  377,  377,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  377,  377,  377,  377,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  377,  377,  377,
      381,  381,  381,  381,  381,  377,  377,  377,  381,  381,
      381,  377,  381,  381,  381,  381,    0,  377,  377,  377,
      377,  377,  377,  377,  377
    } ;

static yyconst flex_int16_t yy_nxt[503] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   19,   20,   21,   22,
       23,   24,   24,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   24,   24,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       24,   24,   49,   55,   89,   92,   96,   90,   97,   56,
       57,   58,   75,   59,   76,   76,   76,   93,   60,   61,
       62,   81,   77,   94,  101,   63,   98,   95,  110,   82,
      102,  133,   64,   77,  134,   99,  108,   65,  135,   66,
       67,  376,  111,  100,   68,  137,   69,  104,  109,   70,

       75,  136,   76,   76,   76,  105,  375,  113,  151,  106,
       77,  114,  152,  138,  139,  158,  158,  120,  140,  115,
      121,   77,  170,  116,  117,  118,  141,  122,  119,   78,
      123,  142,  144,  218,  124,  171,  163,   79,  155,  155,
      155,  374,  193,  143,  145,   75,  164,   76,   76,   76,
      173,  178,  156,  156,  194,   77,  157,  157,  157,  210,
      216,  373,  222,  372,  174,  179,   77,  155,  155,  155,
      371,  219,  211,  217,  223,  227,  157,  157,  157,  157,
      157,  157,  158,  158,  274,  274,  227,  370,  275,  275,
      275,  275,  275,  275,  275,  275,  275,   51,  369,   51,

       51,   51,   51,   51,   53,   53,   54,  368,   54,   54,
       54,   54,   54,   85,   85,   85,   85,   88,   88,  130,
      130,  130,  130,  159,  159,  161,  161,  161,  161,  161,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,

      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  162,  226,
      225,  224,  221,  220,  215,  214,  213,  212,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  192,  191,  190,  189,  188,  187,  186,

      185,  184,  183,  182,  181,  180,  177,  176,  175,  172,
      169,  168,  167,  166,  165,  162,  160,  154,  153,  150,
      149,  148,  147,  146,  132,  131,   52,  129,  128,  127,
      126,  125,  112,  107,  103,   91,   87,   86,   84,   83,
       80,   74,   73,   72,   71,   52,   50,  377,    3,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377
    } ;

static yyconst flex_int16_t yy_chk[503] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   11,   30,   32,   34,   30,   34,   11,
       11,   11,   19,   11,   19,   19,   19,   32,   11,   11,
       11,   21,   19,   33,   36,   11,   35,   33,   41,   21,
       36,   57,   11,   19,   57,   35,   40,   11,   58,   11,
       11,  375,   41,   35,   11,   59,   11,   38,   40,   11,

       18,   58,   18,   18,   18,   38,  374,   43,   68,   38,
       18,   43,   68,   59,   60,   78,   78,   44,   60,   43,
       44,   18,   95,   43,   43,   43,   60,   44,   43,   18,
       44,   61,   62,  148,   44,   95,   89,   18,   75,   75,
       75,  373,  117,   61,   62,   76,   89,   76,   76,   76,
       97,  102,   77,   77,  117,   76,   77,   77,   77,  140,
      147,  371,  151,  366,   97,  102,   76,  155,  155,  155,
      365,  148,  140,  147,  151,  155,  156,  156,  156,  157,
      157,  157,  158,  158,  227,  227,  155,  362,  227,  227,
      227,  274,  274,  274,  275,  275,  275,  378,  361,  378,

      378,  378,  378,  378,  379,  379,  380,  360,  380,  380,
      380,  380,  380,  381,  381,  381,  381,  382,  382,  383,
      383,  383,  383,  384,  384,  385,  385,  385,  385,  385,
      359,  358,  357,  354,  351,  349,  348,  347,  346,  344,
      343,  342,  341,  339,  338,  337,  336,  334,  332,  331,
      329,  328,  327,  326,  325,  324,  323,  320,  318,  316,
      315,  314,  313,  312,  310,  309,  308,  307,  306,  305,
      304,  303,  300,  297,  296,  295,  294,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  280,  279,  278,  276,
      272,  271,  270,  269,  266,  264,  262,  261,  260,  258,

      254,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  236,  235,  233,  232,
      229,  228,  226,  225,  224,  223,  222,  221,  220,  219,
      217,  216,  211,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  189,  188,  187,
      185,  182,  181,  179,  178,  177,  176,  175,  174,  173,
      172,  170,  169,  168,  167,  166,  165,  163,  161,  154,
      153,  152,  150,  149,  146,  145,  143,  141,  138,  136,
      134,  131,  128,  127,  126,  125,  124,  123,  122,  121,
      120,  119,  118,  116,  115,  114,  113,  112,  111,  110,

      109,  107,  106,  105,  104,  103,  100,   99,   98,   96,
       94,   93,   92,   91,   90,   88,   81,   70,   69,   67,
       66,   65,   64,   63,   56,   55,   51,   49,   48,   47,
       46,   45,   42,   39,   37,   31,   26,   25,   23,   22,
       20,   17,   16,   15,   14,    8,    7,    3,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lib/lexer.lxx"
/* -*- mode: C++; c-basic-offset: 2; indent-tabs-mode: nil -*- */
/*
 *  Main authors:
 *     Guido Tack <tack@gecode.org>
 *
 *  Copyright:
 *     Guido Tack, 2007
 *
 *  Last modified:
 *     $Date: 2012-03-02 11:58:58 +1100 (Fri, 02 Mar 2012) $ by $Author: tack $
 *     $Revision: 1278 $
 *
 *  Permission is hereby granted, free of charge, to any person obtaining
 *  a copy of this software and associated documentation files (the
 *  "Software"), to deal in the Software without restriction, including
 *  without limitation the rights to use, copy, modify, merge, publish,
 *  distribute, sublicense, and/or sell copies of the Software, and to
 *  permit persons to whom the Software is furnished to do so, subject to
 *  the following conditions:
 *
 *  The above copyright notice and this permission notice shall be
 *  included in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 *  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 *  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 *  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#line 39 "lib/lexer.lxx"
#if defined __GNUC__
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wsign-compare"
#elif defined _MSC_VER
#pragma warning(push, 1)
#endif

#include <minizinc/parser.hh>

namespace MiniZinc{ class Location; }
#define YYLTYPE MiniZinc::Location
#define YYLTYPE_IS_DECLARED 1

int yy_input_proc(char* buf, int size, yyscan_t yyscanner);
#define YY_INPUT(buf, result, max_size) \
  result = yy_input_proc(buf, max_size, yyscanner);

#define YY_USER_ACTION \
  { MiniZinc::ParserState* parm =  \
    static_cast<MiniZinc::ParserState*>(yyget_extra(yyscanner)); \
    yylloc->first_line = yylloc->last_line = parm->lineno; \
  }

void beginToken(void* parm, YYLTYPE* yyloc, char* t) {
  MiniZinc::ParserState* pp =
    static_cast<MiniZinc::ParserState*>(parm);
  int tokenLength = strlen(t);
  yyloc->first_column = pp->nTokenNextStart;
  pp->nTokenNextStart += tokenLength;
  yyloc->last_column = pp->nTokenNextStart-1;
}

#line 744 "lib/lexer.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

int yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * yyget_lval (yyscan_t yyscanner );

void yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *yyget_lloc (yyscan_t yyscanner );
    
        void yyset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 74 "lib/lexer.lxx"


#line 993 "lib/lexer.yy.cpp"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 378 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 449 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 76 "lib/lexer.lxx"
{ MiniZinc::ParserState* parm =
                      static_cast<MiniZinc::ParserState*>(
                        yyget_extra(yyscanner));
                    parm->lineno++;
                    parm->lineStartPos += parm->nTokenNextStart;
                    parm->nTokenNextStart=1;
                  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 83 "lib/lexer.lxx"
{ /* ignore whitespace */
                    beginToken(yyget_extra(yyscanner), yylloc, yytext);
                  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 86 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_LEFT_BRACKET; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 88 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_LEFT_2D_BRACKET; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 90 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_RIGHT_BRACKET; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 92 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_RIGHT_2D_BRACKET; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 94 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    /* ignore comments */ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 97 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->iValue = 1; return MZN_BOOL_LITERAL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 99 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->iValue = 0; return MZN_BOOL_LITERAL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 101 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->iValue = atoi(yytext); return MZN_INTEGER_LITERAL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 103 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->iValue = atoi(yytext); return MZN_INTEGER_LITERAL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 105 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->iValue = atoi(yytext); return MZN_INTEGER_LITERAL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 107 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->dValue = strtod(yytext,NULL);
                    return MZN_FLOAT_LITERAL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 110 "lib/lexer.lxx"
{
                    beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->dValue = strtod(yytext,NULL);
                    return MZN_FLOAT_LITERAL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 114 "lib/lexer.lxx"
{
                    beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->dValue = strtod(yytext,NULL);
                    return MZN_FLOAT_LITERAL; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "lib/lexer.lxx"
{ 
                    beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return *yytext; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 121 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_DOTDOT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 123 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_COLONCOLON; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 125 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_UNDERSCORE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 127 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_ANN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 129 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_ANNOTATION; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 131 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_ANY; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 133 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_ARRAY; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 135 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_BOOL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 137 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_CASE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 139 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_CONSTRAINT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 141 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_DEFAULT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 143 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_IDIV; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 145 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_IDIV_QUOTED; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 147 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_DIFF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 149 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_DIFF_QUOTED; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 151 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_ELSE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 153 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_ELSEIF; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 155 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_ENDIF; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 157 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_ENUM; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 159 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_FLOAT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 161 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_FUNCTION; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 163 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_IF; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 165 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_INCLUDE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 167 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_INTERSECT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 169 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_INTERSECT_QUOTED; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 171 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_IN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 173 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_IN_QUOTED; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 175 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_INT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 177 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_LET; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 179 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->bValue = false; return MZN_MAXIMIZE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 181 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->bValue = true; return MZN_MINIMIZE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 183 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_MOD; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 185 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_MOD_QUOTED; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 187 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_NOT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 189 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_NOT_QUOTED; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 191 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_OF; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 193 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_SATISFY; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 195 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_OUTPUT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 197 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_PAR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 199 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_PREDICATE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 201 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_RECORD; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 203 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_SET; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 205 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_SOLVE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 207 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_STRING; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 209 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_SUBSET; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 211 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_SUBSET_QUOTED; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 213 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_SUPERSET; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 215 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_SUPERSET_QUOTED; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 217 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_SVAR; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 219 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_SYMDIFF; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 221 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_SYMDIFF_QUOTED; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 223 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_TEST; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 225 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_THEN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 227 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_TUPLE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 229 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_TYPE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 231 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_UNION; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 233 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_UNION_QUOTED; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 235 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_VAR; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 237 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_VARIANT_RECORD; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 239 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_WHERE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 241 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_XOR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 243 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_XOR_QUOTED; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 245 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_PLUS; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 247 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_PLUS_QUOTED; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 249 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_MINUS; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 251 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_MINUS_QUOTED; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 253 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_MULT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 255 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_MULT_QUOTED; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 257 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_DIV; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 259 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_DIV_QUOTED; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 261 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_PLUSPLUS; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 263 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_PLUSPLUS_QUOTED; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 265 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_LE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 267 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_LE_QUOTED; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 269 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_LQ; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 271 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_LQ_QUOTED; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 273 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_GR; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 275 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_GR_QUOTED; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 277 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_GQ; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 279 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_GQ_QUOTED; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 281 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_EQ; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 283 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_EQ_QUOTED; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 285 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_EQ; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 287 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_EQ_QUOTED; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 289 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_NQ; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 291 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_NQ_QUOTED; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 293 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_IMPL; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 295 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_IMPL_QUOTED; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 297 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_RIMPL; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 299 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_RIMPL_QUOTED; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 301 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_EQUIV; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 303 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_EQUIV_QUOTED; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 305 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_OR; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 307 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_OR_QUOTED; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 309 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_AND; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 311 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return MZN_AND_QUOTED; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 313 "lib/lexer.lxx"
{
                    beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->sValue = strdup(yytext); return MZN_IDENTIFIER; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 316 "lib/lexer.lxx"
{
                    beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->sValue = strdup(yytext+1); return MZN_TI_IDENTIFIER; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 319 "lib/lexer.lxx"
{
                    beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->sValue = strdup(yytext+1);
                    yylval->sValue[strlen(yytext)-2] = 0; 
                    return MZN_STRING_LITERAL; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 324 "lib/lexer.lxx"
{
                    beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    yylval->sValue = strdup(yytext+1);
                    yylval->sValue[strlen(yytext)-2] = 0; 
                    return MZN_QUOTED_IDENTIFIER; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 329 "lib/lexer.lxx"
{ beginToken(yyget_extra(yyscanner), yylloc, yytext);
                    return UNKNOWN_CHAR; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 331 "lib/lexer.lxx"
ECHO;
	YY_BREAK
#line 1808 "lib/lexer.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 378 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 378 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 377);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 331 "lib/lexer.lxx"


int yy_input_proc(char* buf, int size, yyscan_t yyscanner) {
  MiniZinc::ParserState* parm = 
    static_cast<MiniZinc::ParserState*>(yyget_extra(yyscanner));
  return parm->fillBuffer(buf, size);
  // work around warning that yyunput is unused
  yyunput (0,buf,yyscanner);
}

